<script setup lang="ts">
const imageWidth = ref<number>(0);
const imageHeight = ref<number>(0);
const warning = ref<string>('');
let canvasElement: HTMLCanvasElement;

onMounted(() => {
  canvasElement = document.getElementById("canvas") as HTMLCanvasElement;
})

function generate(): void {
  if (canvasElement) {
    if (imageWidth.value >= 20000 || imageHeight.value >= 20000) {
      warning.value = "The size cannot be greater than 20000."
      return;
    } else {
      warning.value = "";
    }

    const context = canvasElement.getContext('2d');

    canvasElement.width = imageWidth.value;
    canvasElement.height = imageHeight.value;

    if (context) {
      context.font = `${canvasElement.width / 7}px Inter`;

      context.fillStyle = '#ffffff';
      context.fillRect(0, 0, imageWidth.value, imageHeight.value);

      context.fillStyle = '#1e1e1e';
      context.textAlign = 'center';
      context.textBaseline = 'middle'
      context.fillText(`${imageWidth.value}x${imageHeight.value}`, imageWidth.value / 2, imageHeight.value / 2);
    }
  }
}

function download(type: 'png' | 'jpeg'): void {
  if (canvasElement) {
    const link = document.createElement("a");

    if (type === 'png') {
      link.href = canvasElement.toDataURL("image/png");
    } else if (type === 'jpeg') {
      link.href = canvasElement.toDataURL("image/jpeg");
    }

    link.download = "download.png";
    link.click();
  }
}
</script>

<template>
  <div class="w-100vw h-100vh flex items-center justify-center">
    <div>
      <div class="bg-white w-400px h-auto b-(solid 1px gray-2) rounded-18px p-10px">
        <p class="text-center mb-6px font-en text-14px text-gray-7">Options</p>
        <COption v-model="imageWidth" id="imageWidth" label="Width" type="number" placeholder="1920" />
        <COption v-model="imageHeight" id="imageHeight" label="Height" type="number" placeholder="1080" />
        <hr class="my-10px" />
        <div class="flex gap-5px items-center">
          <CButton label="Generate" @click="generate()" />
          <CButton label="Download (.png)" @click="download('png')" />
          <CButton label="Download (.jpeg)" @click="download('jpeg')" />
        </div>
        <p class="font-en text-orange-4 text-14px">{{ warning }}</p>
      </div>
<!--      <div class="bg-white w-400px h-auto b-(solid 1px gray-2) rounded-18px my-8px p-10px">-->
<!--        <p class="font-en text-gray-8 text-14px">API: https://dummify.netlify.app/api/image?w={{ imageWidth }}&h={{ imageHeight }}</p>-->
<!--        <p class="font-en text-orange-4 text-14px">Warning: For performance reasons, there's no text in the image generated by the API.</p>-->
<!--      </div>-->
      <div class="bg-white w-400px h-auto b-(solid 1px gray-2) rounded-18px my-10px">
        <div class="p-10px">
          <p class="text-center mb-6px font-en text-14px text-gray-7">Result (Scaled down)</p>
        </div>
        <div class="flex items-center justify-center">
          <canvas id="canvas" class="max-w-300px"></canvas>
        </div>
      </div>
    </div>
    <footer class="font-en absolute bottom-180px text-14px text-gray-5 font-600">
      <p>© 2025 Axuata - This project is licensed under the MIT License.</p>
    </footer>
  </div>
</template>

<style scoped>

</style>